---
abstract: 'Perl extension for Berkeley DB version 2, 3, 4, 5 or 6'
author:
  - 'Paul Marquess <pmqs@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: BerkeleyDB
no_index:
  directory:
    - t
    - inc
resources:
  bugtracker: https://github.com/pmqs/BerkeleyDB/issues
  homepage: https://github.com/pmqs/BerkeleyDB
  repository: git://github.com/pmqs/BerkeleyDB.git
version: '0.64'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
